<template>
  <t-table rowKey="index" :data="listData" :columns="columns" :headerAffixedTop="true" :tableLayout="'auto'" />
</template>
<script>
export default {
  data() {
    return {
      listData: [
        {
          category: '故障',
          create_method: '手动',
          current_handler: 'nolanyan',
          current_product: 'T2000',
          current_queue: '客服',
          description: '1  ',
          id: 81526,
          priority: 'L5',
          product: 'T2000',
          product_int: 1,
          report_time: '2022-11-14 10:25:09',
          reporter: 'mfunchen',
          source: '测试同步prod0',
          status: '处理中',
          showHandover: true,
        },
        {
          category: '故障',
          create_method: '手动',
          current_handler: 'nolanyan',
          current_product: 'TGW',
          current_queue: '产品',
          description: '111  ',
          id: 81495,
          priority: 'L5',
          product: 'T2000',
          product_int: 1,
          report_time: '2022-09-19 17:32:50',
          reporter: 'sicilydeng',
          source: '测试同步prod0',
          status: '处理中',
          title: '111',
          showHandover: true,
        },
        {
          category: '测试添加',
          create_method: '手动',
          current_handler: 'nolanyan',
          current_product: 'TGW',
          current_queue: '客服',
          description: '测试  ',
          id: 81491,
          priority: 'L5',
          product: 'T2000',
          product_int: 1,
          report_time: '2022-09-15 14:40:45',
          reporter: 'nolanyan',
          source: '测试同步prod0',
          status: '处理中',
          title: '111',
          showHandover: true,
        },
        {
          category: '故障',
          create_method: '手动',
          current_handler: 'nolanyan',
          current_product: 'T2000',
          current_queue: '客服',
          description: '测试  ',
          id: 81490,
          priority: 'L5',
          product: 'T2000',
          product_int: 1,
          report_time: '2022-09-15 14:32:25',
          reporter: 'nolanyan',
          source: '测试同步prod0',
          status: '处理中',
          title: '1121',
          showHandover: true,
        },
        {
          category: '故障',
          create_method: '手动',
          current_handler: 'nolanyan',
          current_product: 'T2000',
          current_queue: '客服',
          description: '1  ',
          id: 81480,
          priority: 'L5',
          product: 'T2000',
          product_int: 1,
          report_time: '2022-09-13 16:09:11',
          reporter: 'mfunchen',
          source: '测试同步prod0',
          status: '处理中',
          title: 'mfunchen测试拒绝权限',
          showHandover: true,
        },
        {
          category: '故障',
          create_method: '手动',
          current_handler: 'nolanyan',
          current_product: 'T2000',
          current_queue: '客服',
          description: '111  ',
          id: 81473,
          priority: 'L5',
          product: 'T2000',
          product_int: 1,
          report_time: '2022-09-13 10:03:20',
          reporter: 'katchen',
          source: '测试同步prod0',
          status: '处理中',
          showHandover: true,
        },
        {
          category: '故障',
          create_method: '手动',
          current_handler: 'nolanyan',
          current_product: 'T2000',
          current_queue: '客服',
          description: '1212  ',
          id: 81449,
          priority: 'L5',
          product: 'T2000',
          product_int: 1,
          report_time: '2022-09-07 12:50:14',
          reporter: 'nolanyan',
          source: '测试同步prod0',
          status: '用户同意延期处理',
          title: '111',
          showHandover: true,
        },
        {
          category: '故障',
          create_method: '手动',
          current_handler: 'nolanyan',
          current_product: 'TGW',
          current_queue: '开发',
          description: '123  ',
          id: 81408,
          priority: 'L5',
          product: 'T2000',
          product_int: 1,
          report_time: '2022-08-19 11:00:35',
          reporter: 'mfunchen',
          source: '测试同步prod0',
          status: '处理中',
          title: 'mfunchen回退',
          showHandover: true,
        },
        {
          category: '故障',
          create_method: '手动',
          current_handler: 'nolanyan',
          current_product: 'T2000',
          current_queue: '客服',
          description: '123  ',
          id: 81373,
          priority: 'L5',
          product: 'T2000',
          product_int: 1,
          report_time: '2022-08-17 16:44:37',
          reporter: 'mfunchen',
          source: '测试同步prod0',
          status: '处理中',
          title: '测试',
          showHandover: true,
        },
      ],
      columns: [
        {
          title: '工单ID',
          align: 'left',
          width: 150,
          fixed: 'left',
          colKey: 'id',
          sorter: true,
          ellipsis: true,
          ellipsisTitle: true,
        },
        {
          title: '建单方式',
          align: 'left',
          width: 150,
          fixed: false,
          colKey: 'create_method',
          sorter: true,
          ellipsis: true,
          ellipsisTitle: true,
        },
        {
          title: '工单状态',
          align: 'left',
          width: 150,
          fixed: false,
          colKey: 'status',
          sorter: true,
          ellipsis: true,
          ellipsisTitle: true,
        },
        {
          title: '工单分类',
          align: 'left',
          width: 150,
          fixed: false,
          colKey: 'category',
          sorter: true,
          ellipsis: true,
          ellipsisTitle: true,
        },
        {
          title: '优先级',
          align: 'left',
          width: 150,
          fixed: false,
          colKey: 'priority',
          sorter: true,
          ellipsis: true,
          ellipsisTitle: true,
        },
        {
          title: '当前队列所属产品',
          align: 'left',
          width: 150,
          fixed: false,
          colKey: 'current_product',
          sorter: true,
          ellipsis: true,
          ellipsisTitle: true,
        },
        {
          title: '当前处理人队列',
          align: 'left',
          width: 150,
          fixed: false,
          colKey: 'current_queue',
          sorter: true,
          ellipsis: true,
          ellipsisTitle: true,
        },
        {
          title: '描述',
          align: 'left',
          width: 150,
          fixed: false,
          colKey: 'description',
          sorter: true,
          ellipsis: true,
          ellipsisTitle: true,
        },
        {
          title: '反馈人',
          align: 'left',
          width: 150,
          fixed: false,
          colKey: 'reporter',
          sorter: true,
          ellipsis: true,
          ellipsisTitle: true,
        },
        {
          title: '产品',
          align: 'left',
          width: 150,
          fixed: false,
          colKey: 'product',
          sorter: true,
          ellipsis: true,
          ellipsisTitle: true,
        },
        {
          title: '来源',
          align: 'left',
          width: 150,
          fixed: false,
          colKey: 'source',
          sorter: true,
          ellipsis: true,
          ellipsisTitle: true,
        },
        {
          title: '反馈时间',
          align: 'left',
          width: 150,
          fixed: false,
          colKey: 'report_time',
          sorter: true,
          ellipsis: true,
          ellipsisTitle: true,
        },
        {
          title: 'TAPD地址',
          align: 'left',
          width: 150,
          fixed: false,
          colKey: 'tapd_address',
          sorter: true,
          ellipsis: true,
          ellipsisTitle: true,
        },
        {
          title: '标题',
          align: 'left',
          width: 150,
          fixed: false,
          colKey: 'title',
          sorter: true,
          ellipsis: true,
          ellipsisTitle: true,
        },
        {
          title: '排查列表',
          align: 'left',
          width: 150,
          fixed: false,
          colKey: 'analyze_list',
          sorter: true,
          ellipsis: true,
          ellipsisTitle: true,
        },
        {
          title: '复现-风险次数',
          align: 'left',
          width: 150,
          fixed: false,
          colKey: 'risk_count_recurrent',
          sorter: true,
          ellipsis: true,
          ellipsisTitle: true,
        },
        {
          title: '工单风险分数',
          align: 'left',
          width: 150,
          fixed: false,
          colKey: 'risk_score',
          sorter: true,
          ellipsis: true,
          ellipsisTitle: true,
        },
        {
          title: '情绪激动-风险次数',
          align: 'left',
          width: 150,
          fixed: false,
          colKey: 'risk_count_emotional',
          sorter: true,
          ellipsis: true,
          ellipsisTitle: true,
        },
      ],
    };
  },
};
</script>
